# Generated by Django 4.2.11 on 2024-07-19 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='basic_mcq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ques_description', models.TextField(max_length=700)),
                ('Option1', models.TextField(max_length=200)),
                ('Option2', models.TextField(max_length=200)),
                ('Option3', models.TextField(max_length=200)),
                ('Option4', models.TextField(max_length=200)),
            ],
        ),
    ]
