# Generated by Django 4.2.11 on 2024-07-19 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='basic_mcq',
            name='answers',
            field=models.TextField(default='Earth', max_length=200),
            preserve_default=False,
        ),
    ]
