# Generated by Django 4.2.11 on 2024-07-19 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0002_basic_mcq_answers'),
    ]

    operations = [
        migrations.CreateModel(
            name='basic_fbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ques_description', models.TextField(max_length=700)),
                ('answers', models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='basic_tf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ques_description', models.TextField(max_length=700)),
                ('answers', models.TextField(max_length=200)),
            ],
        ),
    ]
